package cl.com.ccla.webservice.wsdashboard;

import javax.xml.ws.WebFault;

@WebFault(faultBean="cl.com.ccla.type.wsdashboard.Exception",
  targetNamespace="http://dashboard.ws.ccla.cl", name="Exception")
public class Exception
  extends java.lang.Exception
{
  private cl.com.ccla.type.wsdashboard.Exception faultInfo;

  public Exception(String message,
                   cl.com.ccla.type.wsdashboard.Exception faultInfo)
  {
    super(message);
    this.faultInfo = faultInfo;
  }

  public Exception(String message,
                   cl.com.ccla.type.wsdashboard.Exception faultInfo,
                   Throwable t)
  {
    super(message,t);
    this.faultInfo = faultInfo;
  }

  public cl.com.ccla.type.wsdashboard.Exception getFaultInfo()
  {
    return faultInfo;
  }

  public void setFaultInfo(cl.com.ccla.type.wsdashboard.Exception faultInfo)
  {
    this.faultInfo = faultInfo;
  }
}
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)
