package cl.com.ccla.webservice.dashnotif;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl",
  targetNamespace="http://producto.notificacion.dashboard.ws.ccla.cl/",
  name="WSDSHNotifProdPortBindingQSService")
public class WSDSHNotifProdPortBindingQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("cl.com.ccla.webservice.dashnotif.WSDSHNotifProdPortBindingQSService");
      URL baseUrl =
        WSDSHNotifProdPortBindingQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            WSDSHNotifProdPortBindingQSService.class.getResource("http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl",
          e);
    }
  }

  public WSDSHNotifProdPortBindingQSService()
  {
    super(wsdlLocationURL,
          new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                    "WSDSHNotifProdPortBindingQSService"));
  }

  public WSDSHNotifProdPortBindingQSService(URL wsdlLocation,
                                            QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="WSDSHNotifProdPortBindingQSPort")
  public cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF getWSDSHNotifProdPortBindingQSPort()
  {
    return (cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF) super.getPort(new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                                                                                       "WSDSHNotifProdPortBindingQSPort"),
                                                                             cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF.class);
  }

  @WebEndpoint(name="WSDSHNotifProdPortBindingQSPort")
  public cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF getWSDSHNotifProdPortBindingQSPort(WebServiceFeature... features)
  {
    return (cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF) super.getPort(new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                                                                                       "WSDSHNotifProdPortBindingQSPort"),
                                                                             cl.com.ccla.webservice.dashnotif.WSDSHNotifProdIF.class,
                                                                             features);
  }
}
