package cl.com.ccla.webservice.dashnotif;

import cl.com.ccla.webservice.dashnotif.Exception;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion?wsdl",
  targetNamespace="http://producto.notificacion.dashboard.ws.ccla.cl/",
  name="WSDSHNotifProdIF")
@XmlSeeAlso(
  { cl.com.ccla.type.dashnotif.ObjectFactory.class })
@SOAPBinding(style=Style.RPC)
public interface WSDSHNotifProdIF
{
  @WebMethod
  @Action(input="http://producto.notificacion.dashboard.ws.ccla.cl/WSDSHNotifProdIF/notificarTrxWPRequest", fault =
      { @FaultAction(value="http://producto.notificacion.dashboard.ws.ccla.cl/WSDSHNotifProdIF/notificarTrxWP/Fault/Exception",
          className = Exception.class) }, output="http://producto.notificacion.dashboard.ws.ccla.cl/WSDSHNotifProdIF/notificarTrxWPResponse")
  @WebResult(partName="NotificarTrx_WPRS", name="NotificarTrx_WPRS")
  public cl.com.ccla.type.dashnotif.RSNotificarTrxWP notificarTrxWP(@WebParam(partName="NotificarTrx_WPRQ",
      name="NotificarTrx_WPRQ")
    cl.com.ccla.type.dashnotif.RQNotificarTrxWP NotificarTrx_WPRQ)
    throws cl.com.ccla.webservice.dashnotif.Exception;
}
