package cl.com.ccla.webservice.consultahistorialturismo;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl",
  targetNamespace="http://ccla.cl/enterprise/catalogo/ebs/region", name="ConsultarHistorialTurismoBindingQSService")
public class ConsultarHistorialTurismoBindingQSService
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoBindingQSService");
      URL baseUrl =
        ConsultarHistorialTurismoBindingQSService.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            ConsultarHistorialTurismoBindingQSService.class.getResource("http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl",
          e);
    }
  }

  public ConsultarHistorialTurismoBindingQSService()
  {
    super(wsdlLocationURL,
          new QName("http://ccla.cl/enterprise/catalogo/ebs/region",
                    "ConsultarHistorialTurismoBindingQSService"));
  }

  public ConsultarHistorialTurismoBindingQSService(URL wsdlLocation,
                                                   QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="ConsultarHistorialTurismoBindingQSPort")
  public cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType getConsultarHistorialTurismoBindingQSPort()
  {
    return (cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType) super.getPort(new QName("http://ccla.cl/enterprise/catalogo/ebs/region",
                                                                                                                                "ConsultarHistorialTurismoBindingQSPort"),
                                                                                                                      cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType.class);
  }

  @WebEndpoint(name="ConsultarHistorialTurismoBindingQSPort")
  public cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType getConsultarHistorialTurismoBindingQSPort(WebServiceFeature... features)
  {
    return (cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType) super.getPort(new QName("http://ccla.cl/enterprise/catalogo/ebs/region",
                                                                                                                                "ConsultarHistorialTurismoBindingQSPort"),
                                                                                                                      cl.com.ccla.webservice.consultahistorialturismo.ConsultarHistorialTurismoOperacionPortType.class,
                                                                                                                      features);
  }
}
