package cl.com.ccla.webservice.consultahistorialturismo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/Consulta/HistorialTurismo?wsdl",
  targetNamespace="http://ccla.cl/enterprise/catalogo/ebs/region", name="ConsultarHistorialTurismoOperacionPortType")
@XmlSeeAlso(
  { cl.com.ccla.type.consultahistorialturismo.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface ConsultarHistorialTurismoOperacionPortType
{
  @WebMethod(operationName="ConsultarHistorialTurismo", action="http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarHistorialTurismo")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarHistorialTurismo",
    output="http://ccla.cl/enterprise/catalogo/ebs/region/ConsultarHistorialTurismoOperacionPortType/ConsultarHistorialTurismoResponse")
  @WebResult(targetNamespace="http://ccla.cl/enterprise/catalogo/ebm/historialTurismo",
    partName="parameter", name="EntConsultarHistorialTurismoOutEBM")
  public cl.com.ccla.type.consultahistorialturismo.EntConsultarHistorialTurismoOutResTYPE consultarHistorialTurismo(@WebParam(targetNamespace="http://ccla.cl/enterprise/catalogo/ebm/historialTurismo",
      partName="parameters", name="EntConsultarHistorialTurismoInEBM")
    cl.com.ccla.type.consultahistorialturismo.EntConsultarHistorialTurismoInReqType parameters,
    @WebParam(targetNamespace="http://esb.cla.cl/EnterpriseObjects/CCLAMWClients/V1",
      partName="requestHeader", name="CCLAMWClients", header=true)
    cl.com.ccla.type.consultahistorialturismo.CCLAMWClientsType requestHeader);
}
