package cl.com.ccla.webservice;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebServiceClient(wsdlLocation = "http://merelava:8080/TbkAppv1/TbkWS?wsdl",
                  targetNamespace = "http://ws/", name = "TbkWS")
public class TbkWS_Service extends Service {
    private static URL wsdlLocationURL;

    private static Logger logger;
    static {
        try {
            logger = Logger.getLogger("cl.com.ccla.webservice.TbkWS_Service");
            URL baseUrl = TbkWS_Service.class.getResource(".");
            if (baseUrl == null) {
                wsdlLocationURL =
                        TbkWS_Service.class.getResource("http://merelava:8080/TbkAppv1/TbkWS?wsdl");
                if (wsdlLocationURL == null) {
                    baseUrl = new File(".").toURL();
                    wsdlLocationURL =
                            new URL(baseUrl, "http://merelava:8080/TbkAppv1/TbkWS?wsdl");
                }
            } else {
                if (!baseUrl.getPath().endsWith("/")) {
                    baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
                }
                wsdlLocationURL =
                        new URL(baseUrl, "http://merelava:8080/TbkAppv1/TbkWS?wsdl");
            }
        } catch (MalformedURLException e) {
            logger.log(Level.ALL,
                       "Failed to create wsdlLocationURL using http://merelava:8080/TbkAppv1/TbkWS?wsdl",
                       e);
        }
    }

    public TbkWS_Service() {
        super(wsdlLocationURL, new QName("http://ws/", "TbkWS"));
    }

    public TbkWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @WebEndpoint(name = "TbkWSPort")
    public cl.com.ccla.webservice.TbkWS getTbkWSPort() {
        return (cl.com.ccla.webservice.TbkWS)super.getPort(new QName("http://ws/",
                                                                     "TbkWSPort"),
                                                           cl.com.ccla.webservice.TbkWS.class);
    }

    @WebEndpoint(name = "TbkWSPort")
    public cl.com.ccla.webservice.TbkWS getTbkWSPort(WebServiceFeature... features) {
        return (cl.com.ccla.webservice.TbkWS)super.getPort(new QName("http://ws/",
                                                                     "TbkWSPort"),
                                                           cl.com.ccla.webservice.TbkWS.class,
                                                           features);
    }
}
