package cl.com.ccla.webservice;

import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

public class TbkWSPortClient {
    @WebServiceRef
    private static TbkWS_Service tbkWS_Service;

    public static void main(String[] args) {
        tbkWS_Service = new TbkWS_Service();
        TbkWS tbkWS = tbkWS_Service.getTbkWSPort();
        // Add your code to call the desired methods.
    }
}
