package cl.com.ccla.webservice.historialpagoturismoagregar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl",
  targetNamespace="http://www.ccla.cl/HistorialPagoTurismoAgregar", name="HistorialPagoTurismoAgregar")
@XmlSeeAlso(
  { cl.com.ccla.type.historialpagoturismoagregar.ObjectFactory.class })
@SOAPBinding(style=Style.DOCUMENT, parameterStyle=ParameterStyle.BARE)
public interface HistorialPagoTurismoAgregar
{
  @WebMethod(operationName="PagoTurismoAgregar", action="http://www.ccla.cl/HistorialPagoTurismoAgregar/NewOperation")
  @SOAPBinding(parameterStyle=ParameterStyle.BARE)
  @Action(input="http://www.ccla.cl/HistorialPagoTurismoAgregar/NewOperation",
    output="http://www.ccla.cl/HistorialPagoTurismoAgregar/HistorialPagoTurismoAgregar/PagoTurismoAgregarResponse")
  @WebResult(targetNamespace="http://www.ccla.cl/HistorialPagoTurismoResp",
    partName="parameters", name="HistorialPagoTurismoResp")
  public cl.com.ccla.type.historialpagoturismoagregar.ResponseHistorialPagoTurismoTYPE pagoTurismoAgregar(@WebParam(targetNamespace="http://www.ccla.cl/HistorialPagoTurismoReq",
      partName="parameters", name="RequestHistorial")
    cl.com.ccla.type.historialpagoturismoagregar.RequestHistorialTurismoTYPE parameters);
}
