package cl.com.ccla.mpe.webservice.DBNotificacion;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebServiceClient(wsdlLocation =
                  "http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion/Proxy/WS_DSH_Notif_Prod?wsdl",
                  targetNamespace =
                  "http://producto.notificacion.dashboard.ws.ccla.cl/",
                  name = "WSDSHNotifProdService")
public class WSDSHNotifProdService extends Service {
    private static URL wsdlLocationURL;

    private static Logger logger;
    static {
        try {
            logger =
                    Logger.getLogger("cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdService");
            URL baseUrl = WSDSHNotifProdService.class.getResource(".");
            if (baseUrl == null) {
                wsdlLocationURL =
                        WSDSHNotifProdService.class.getResource("http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion/Proxy/WS_DSH_Notif_Prod?wsdl");
                if (wsdlLocationURL == null) {
                    baseUrl = new File(".").toURL();
                    wsdlLocationURL =
                            new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion/Proxy/WS_DSH_Notif_Prod?wsdl");
                }
            } else {
                if (!baseUrl.getPath().endsWith("/")) {
                    baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
                }
                wsdlLocationURL =
                        new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion/Proxy/WS_DSH_Notif_Prod?wsdl");
            }
        } catch (MalformedURLException e) {
            logger.log(Level.ALL,
                       "Failed to create wsdlLocationURL using http://qa-osbweb:8005/Financiero/PagoElectronico/WsDashboardNotificacion/Proxy/WS_DSH_Notif_Prod?wsdl",
                       e);
        }
    }

    public WSDSHNotifProdService() {
        super(wsdlLocationURL,
              new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                        "WSDSHNotifProdService"));
    }

    public WSDSHNotifProdService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @WebEndpoint(name = "WSDSHNotifProdPort")
    public cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF getWSDSHNotifProdPort() {
        return (cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF)super.getPort(new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                                                                                                   "WSDSHNotifProdPort"),
                                                                                         cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF.class);
    }

    @WebEndpoint(name = "WSDSHNotifProdPort")
    public cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF getWSDSHNotifProdPort(WebServiceFeature... features) {
        return (cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF)super.getPort(new QName("http://producto.notificacion.dashboard.ws.ccla.cl/",
                                                                                                   "WSDSHNotifProdPort"),
                                                                                         cl.com.ccla.mpe.webservice.DBNotificacion.WSDSHNotifProdIF.class,
                                                                                         features);
    }
}
