package cl.com.ccla.webservice.historialpagoturismoagregar;

import java.io.File;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebServiceClient(wsdlLocation="http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl",
  targetNamespace="http://www.ccla.cl/HistorialPagoTurismoAgregar", name="HistorialPagoTurismoAgregar")
public class HistorialPagoTurismoAgregar_Service
  extends Service
{
  private static URL wsdlLocationURL;

  private static Logger logger;
  static
  {
    try
    {
      logger = Logger.getLogger("cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar_Service");
      URL baseUrl =
        HistorialPagoTurismoAgregar_Service.class.getResource(".");
      if (baseUrl == null)
      {
        wsdlLocationURL =
            HistorialPagoTurismoAgregar_Service.class.getResource("http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl");
        if (wsdlLocationURL == null)
        {
          baseUrl = new File(".").toURL();
          wsdlLocationURL =
              new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl");
        }
      }
      else
      {
                if (!baseUrl.getPath().endsWith("/")) {
         baseUrl = new URL(baseUrl, baseUrl.getPath() + "/");
}
                wsdlLocationURL =
            new URL(baseUrl, "http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl");
      }
    }
    catch (MalformedURLException e)
    {
      logger.log(Level.ALL,
          "Failed to create wsdlLocationURL using http://qa-osbweb:8005/Financiero/PagoElectronico/HistorialPagoTurismoAgregar/EBS/HistorialPagoTurismoAgregarEBS?wsdl",
          e);
    }
  }

  public HistorialPagoTurismoAgregar_Service()
  {
    super(wsdlLocationURL,
          new QName("http://www.ccla.cl/HistorialPagoTurismoAgregar",
                    "HistorialPagoTurismoAgregar"));
  }

  public HistorialPagoTurismoAgregar_Service(URL wsdlLocation,
                                             QName serviceName)
  {
    super(wsdlLocation, serviceName);
  }

  @WebEndpoint(name="HistorialPagoTurismoAgregarSOAP")
  public cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar getHistorialPagoTurismoAgregarSOAP()
  {
    return (cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar) super.getPort(new QName("http://www.ccla.cl/HistorialPagoTurismoAgregar",
                                                                                                                    "HistorialPagoTurismoAgregarSOAP"),
                                                                                                          cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar.class);
  }

  @WebEndpoint(name="HistorialPagoTurismoAgregarSOAP")
  public cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar getHistorialPagoTurismoAgregarSOAP(WebServiceFeature... features)
  {
    return (cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar) super.getPort(new QName("http://www.ccla.cl/HistorialPagoTurismoAgregar",
                                                                                                                    "HistorialPagoTurismoAgregarSOAP"),
                                                                                                          cl.com.ccla.webservice.historialpagoturismoagregar.HistorialPagoTurismoAgregar.class,
                                                                                                          features);
  }
}
