package cl.com.ccla.webservice.consultadatosturismo;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebService(wsdlLocation =
            "http://qa-osbweb:8005/Financiero/PagoElectronico/ConsultaDatosTurismo?wsdl",
            targetNamespace = "http://ccla.cl/enterprise/catalogo/ebs/region",
            name = "ConsultarDatosTurismoOperacionPortType")
@XmlSeeAlso( { cl.com.ccla.type.consultadatosturismo.ObjectFactory.class })
@SOAPBinding(style = Style.DOCUMENT, parameterStyle = ParameterStyle.BARE)
public interface ConsultarDatosTurismoOperacionPortType {
    @WebMethod(operationName = "ConsultarDatosTurismo",
               action = "http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarDatosTurismo")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @Action(input =
            "http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarDatosTurismo",
            output =
            "http://ccla.cl/enterprise/catalogo/ebs/region/ConsultarDatosTurismoOperacionPortType/ConsultarDatosTurismoResponse")
    @WebResult(targetNamespace =
               "http://ccla.cl/enterprise/catalogo/ebm/datosTurismo",
               partName = "parameter", name = "EntConsultarDatosTurismoOutEBM")
    public cl.com.ccla.type.consultadatosturismo.EntConsultarDatosTurismoOutResTYPE consultarDatosTurismo(@WebParam(targetNamespace =
                                                                                                                    "http://ccla.cl/enterprise/catalogo/ebm/datosTurismo",
                                                                                                                    partName =
                                                                                                                    "parameters",
                                                                                                                    name =
                                                                                                                    "EntConsultarDatosTurismoInEBM")
        cl.com.ccla.type.consultadatosturismo.EntConsultarDatosTurismoInReqType parameters,
        @WebParam(targetNamespace =
                  "http://esb.cla.cl/EnterpriseObjects/CCLAMWClients/V1",
                  partName = "requestHeader", name = "CCLAMWClients",
                  header = true)
        cl.com.ccla.type.consultadatosturismo.CCLAMWClientsType requestHeader);
}
