package cl.com.ccla.webservice.resumencredito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.jws.soap.SOAPBinding.Style;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 150302.2135.55683)

@WebService(wsdlLocation =
            "http://qa-osbweb:8005/Financiero/PagoElectronico/ConsultaResumenCredito?wsdl",
            targetNamespace = "http://ccla.cl/enterprise/catalogo/ebs/region",
            name = "ConsultarResumenCreditoOperacionPortType")
@XmlSeeAlso( { cl.com.ccla.type.resumencredito.ObjectFactory.class })
@SOAPBinding(style = Style.DOCUMENT, parameterStyle = ParameterStyle.BARE)
public interface ConsultarResumenCreditoOperacionPortType {
    @WebMethod(operationName = "ConsultarResumenCredito",
               action = "http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarResumenCredito")
    @SOAPBinding(parameterStyle = ParameterStyle.BARE)
    @Action(input =
            "http://ccla.cl/enterprise/catalogo/ebs/licanciaAfiliado/ConsultarResumenCredito",
            output =
            "http://ccla.cl/enterprise/catalogo/ebs/region/ConsultarResumenCreditoOperacionPortType/ConsultarResumenCreditoResponse")
    @WebResult(targetNamespace =
               "http://ccla.cl/enterprise/catalogo/ebm/resumenCredito",
               partName = "parameter",
               name = "EntConsultarResumenCreditoOutEBM")
    public cl.com.ccla.type.resumencredito.EntConsultarResumenCreditoOutResTYPE consultarResumenCredito(@WebParam(targetNamespace =
                                                                                                                  "http://ccla.cl/enterprise/catalogo/ebm/resumenCredito",
                                                                                                                  partName =
                                                                                                                  "parameters",
                                                                                                                  name =
                                                                                                                  "EntConsultarResumenCreditoInEBM")
        cl.com.ccla.type.resumencredito.EntConsultarResumenCreditoInReqType parameters,
        @WebParam(targetNamespace =
                  "http://esb.cla.cl/EnterpriseObjects/CCLAMWClients/V1",
                  partName = "requestHeader", name = "CCLAMWClients",
                  header = true)
        cl.com.ccla.type.resumencredito.CCLAMWClientsType requestHeader);
}
